"""add must_change_password to user

Revision ID: 96b00c5137a4
Revises: 
Create Date: 2025-10-01 13:47:37.814813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b00c5137a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloads_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_user_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_youtube_id'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_usage_analytics_date'), table_name='usage_analytics')
    op.drop_index(op.f('ix_usage_analytics_id'), table_name='usage_analytics')
    op.drop_table('usage_analytics')
    op.drop_index(op.f('ix_payment_records_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_user_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_payment_history_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_stripe_customer_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_stripe_payment_intent_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_user_id'), table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_system_analytics_date'), table_name='system_analytics')
    op.drop_index(op.f('ix_system_analytics_id'), table_name='system_analytics')
    op.drop_table('system_analytics')
    op.drop_index(op.f('ix_subscription_history_id'), table_name='subscription_history')
    op.drop_table('subscription_history')
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('extra_data', sa.Text(), nullable=True))
    op.alter_column('subscriptions', 'stripe_customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_unique_constraint(None, 'subscriptions', ['stripe_subscription_id'])
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_column('subscriptions', 'stripe_price_id')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'expiry_date')
    op.drop_column('subscriptions', 'payment_id')
    op.drop_column('subscriptions', 'current_period_start')
    op.alter_column('transcript_downloads', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transcript_downloads', 'processing_time',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transcript_downloads', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transcript_downloads', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_transcript_downloads_created_at'), 'transcript_downloads', ['created_at'], unique=False)
    op.create_index('ix_transcripts_user_created', 'transcript_downloads', ['user_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'transcript_downloads', 'users', ['user_id'], ['id'])
    op.drop_column('transcript_downloads', 'video_duration')
    op.drop_column('transcript_downloads', 'download_method')
    op.drop_column('transcript_downloads', 'updated_at')
    op.drop_column('transcript_downloads', 'video_uploader')
    op.drop_column('transcript_downloads', 'ip_address')
    op.drop_column('transcript_downloads', 'video_title')
    op.drop_column('transcript_downloads', 'user_agent')
    op.drop_column('transcript_downloads', 'download_url')
    op.drop_column('transcript_downloads', 'expires_at')
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.VARCHAR(length=20),
               server_default='inactive',
               existing_nullable=False)
    op.alter_column('users', 'usage_clean_transcripts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'usage_unclean_transcripts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'usage_audio_downloads',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'usage_video_downloads',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'usage_reset_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('uq_users_email'), table_name='users')
    op.drop_index(op.f('uq_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'subscription_start_date')
    op.drop_column('users', 'subscription_current_period_end')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'language')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'total_downloads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_downloads', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('subscription_current_period_end', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('subscription_start_date', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('subscription_end_date', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('uq_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('uq_users_email'), 'users', ['email'], unique=1)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'usage_reset_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'usage_video_downloads',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'usage_audio_downloads',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'usage_unclean_transcripts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'usage_clean_transcripts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'must_change_password')
    op.add_column('transcript_downloads', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    op.add_column('transcript_downloads', sa.Column('download_url', sa.TEXT(), nullable=True))
    op.add_column('transcript_downloads', sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True))
    op.add_column('transcript_downloads', sa.Column('video_title', sa.VARCHAR(length=200), nullable=True))
    op.add_column('transcript_downloads', sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True))
    op.add_column('transcript_downloads', sa.Column('video_uploader', sa.TEXT(), nullable=True))
    op.add_column('transcript_downloads', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('transcript_downloads', sa.Column('download_method', sa.VARCHAR(length=50), nullable=True))
    op.add_column('transcript_downloads', sa.Column('video_duration', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transcript_downloads', type_='foreignkey')
    op.drop_index('ix_transcripts_user_created', table_name='transcript_downloads')
    op.drop_index(op.f('ix_transcript_downloads_created_at'), table_name='transcript_downloads')
    op.alter_column('transcript_downloads', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('transcript_downloads', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'completed'"),
               existing_nullable=True)
    op.alter_column('transcript_downloads', 'processing_time',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('transcript_downloads', 'file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('current_period_start', sa.DATETIME(), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('expiry_date', sa.DATETIME(), nullable=False))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.BOOLEAN(), nullable=True))
    op.add_column('subscriptions', sa.Column('current_period_end', sa.DATETIME(), nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', sa.DATETIME(), nullable=False))
    op.add_column('subscriptions', sa.Column('stripe_price_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.alter_column('subscriptions', 'stripe_customer_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('subscriptions', 'extra_data')
    op.drop_column('subscriptions', 'expires_at')
    op.drop_column('subscriptions', 'cancelled_at')
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.create_table('subscription_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('from_tier', sa.VARCHAR(length=20), nullable=True),
    sa.Column('to_tier', sa.VARCHAR(length=20), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('history_metadata', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_history_id'), 'subscription_history', ['id'], unique=False)
    op.create_table('system_analytics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('total_users', sa.INTEGER(), nullable=True),
    sa.Column('new_users', sa.INTEGER(), nullable=True),
    sa.Column('active_users', sa.INTEGER(), nullable=True),
    sa.Column('transcript_downloads', sa.INTEGER(), nullable=True),
    sa.Column('audio_downloads', sa.INTEGER(), nullable=True),
    sa.Column('video_downloads', sa.INTEGER(), nullable=True),
    sa.Column('free_users', sa.INTEGER(), nullable=True),
    sa.Column('pro_users', sa.INTEGER(), nullable=True),
    sa.Column('premium_users', sa.INTEGER(), nullable=True),
    sa.Column('daily_revenue', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_analytics_id'), 'system_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_system_analytics_date'), 'system_analytics', ['date'], unique=False)
    op.create_table('payment_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('subscription_tier', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('payment_metadata', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_history_user_id'), 'payment_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_payment_history_stripe_payment_intent_id'), 'payment_history', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_payment_history_stripe_customer_id'), 'payment_history', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_payment_history_id'), 'payment_history', ['id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('plan_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index(op.f('ix_payment_records_user_id'), 'payment_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_payment_records_id'), 'payment_records', ['id'], unique=False)
    op.create_table('usage_analytics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('total_users', sa.INTEGER(), nullable=True),
    sa.Column('active_users', sa.INTEGER(), nullable=True),
    sa.Column('new_registrations', sa.INTEGER(), nullable=True),
    sa.Column('total_downloads', sa.INTEGER(), nullable=True),
    sa.Column('transcript_downloads', sa.INTEGER(), nullable=True),
    sa.Column('audio_downloads', sa.INTEGER(), nullable=True),
    sa.Column('video_downloads', sa.INTEGER(), nullable=True),
    sa.Column('subscription_upgrades', sa.INTEGER(), nullable=True),
    sa.Column('subscription_cancellations', sa.INTEGER(), nullable=True),
    sa.Column('revenue', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_analytics_id'), 'usage_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_usage_analytics_date'), 'usage_analytics', ['date'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('youtube_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('download_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('download_format', sa.VARCHAR(length=20), nullable=True),
    sa.Column('quality', sa.VARCHAR(length=20), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('processing_time', sa.INTEGER(), nullable=True),
    sa.Column('download_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('download_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_youtube_id'), 'downloads', ['youtube_id'], unique=False)
    op.create_index(op.f('ix_downloads_user_id'), 'downloads', ['user_id'], unique=False)
    op.create_index(op.f('ix_downloads_id'), 'downloads', ['id'], unique=False)
    # ### end Alembic commands ###
